# Generated by Django 4.2.2 on 2023-06-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_country_user_token_user_token_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Создатель'),
        ),
    ]
