# Generated by Django 4.2.2 on 2023-06-15 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_alter_post_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('created_at',), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
