# Generated by Django 4.2.2 on 2023-06-26 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='creator',
        ),
    ]
