# Generated by Django 4.2.2 on 2023-07-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skychimp', '0003_alter_attempt_options_alter_sending_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время рассылки'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.CharField(choices=[('delivered', 'доставлено'), ('not_delivered', 'не доставлено')], verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='frequency',
            field=models.CharField(choices=[('1 раз в день', '1 раз в день'), ('1 раз в неделю', '1 раз в неделю'), ('1 раз в месяц', '1 раз в месяц'), ('Один раз', 'Один раз'), ('1 раз в день', '1 раз в день'), ('1 раз в неделю', '1 раз в неделю'), ('1 раз в месяц', '1 раз в месяц')], max_length=14, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='scheduled_time',
            field=models.TimeField(auto_now_add=True, verbose_name='Время рассылки'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='status',
            field=models.CharField(choices=[('Создана', 'Создана'), ('Завершена', 'Завершена'), ('Запущена', 'Запущена')], default='created', max_length=50, verbose_name='Статус'),
        ),
    ]
