# Generated by Django 4.2.2 on 2023-07-04 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skychimp', '0004_alter_attempt_sent_at_alter_attempt_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='message',
        ),
        migrations.AddField(
            model_name='customer',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='комментарий'),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='имя'),
        ),
    ]
