# Generated by Django 4.2.2 on 2023-07-04 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skychimp', '0005_remove_customer_message_customer_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sending',
            name='created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
        ),
    ]
