# Generated by Django 4.2.2 on 2023-07-09 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skychimp', '0007_customer_is_active_alter_sending_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sending',
            name='created_at',
        ),
        migrations.AddField(
            model_name='sending',
            name='end_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='sending',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='scheduled_time',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Время рассылки'),
        ),
    ]
