# Generated by Django 4.2.2 on 2023-07-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skychimp', '0008_remove_sending_created_at_sending_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sending',
            name='frequency',
            field=models.CharField(choices=[('Один раз', 'Один раз'), ('1 раз в день', '1 раз в день'), ('1 раз в неделю', '1 раз в неделю'), ('1 раз в месяц', '1 раз в месяц')], max_length=14, verbose_name='Периодичность'),
        ),
    ]
