# Generated by Django 4.2.2 on 2023-07-10 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skychimp', '0009_alter_sending_frequency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sending',
            options={'permissions': [('set_send_status', 'Can set sending status')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
